# 错误处理机制

## 1. 概述

默认情况下Go中程序出现panic异常后就会退出。

* 1.Go语言追求简洁优雅，所以Go语言不支持传统的`try...catch...finally`这种处理

* 2.Go中引入的处理方式为：`defer`、`panic`、`recover`

* 3.这几个异常的使用场景可以简单描述为：Go中可以抛出一个panic异常，然后在defer中通过**recover捕获这个异常**，然后正常处理

## 2. error

```go
package main

import (
	"fmt"
)

func main() {
	test()
}
func test() int {
	//使用defer + recover 来捕获和处理异常
	defer func(){
		err := recover() //recover内置函数 捕获异常
		if err!=nil { //如果err不为nil说明出现异常了
			fmt.Println("err=",err)
		}
	}()
	num1 := 10
	num2 := 0
	//这里会抛出异常 runtime error: integer divide by zero
	res := num1 / num2
	return res
}
```

### 自定义错误

Go语言中也支持自定义错误，使用`errors.New()`和`panic`内置函数。

* 1.errors.New("错误说明")会返回一个error类型的值，表示一个错误
* 2.panic内置函数，接收一个interface{}类型的值(也就是任何值了)作为参数。可以接收error类型的变量，**输出错误信息并退出程序**。

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	err := loadConfig("init.conf")
	if err!=nil {
		//如果读取错误则输出错误并终止程序
		panic(err)
	}else {
		fmt.Println("配置文件读取成功，程序继续执行")
	}
}

//函数读取init.conf的配置文件
//如果文件名传入不对就返回自定义错误
func loadConfig(name string)(err error) {
	if name=="init.conf" {
		//正确则读取
		return nil
	}else {
		//否则返回一个自定义错误
		return errors.New("读取文件错误。。")
	}
}
```

## 3. panic

### 1.作用

* 1.停止当前函数执行
* 2.一直向上返回，执行每一层的defer
* 3.如果没有遇见recover则程序退出

### 2. recover

* 1.仅在defer调用中使用
* 2.获取panic的值
* 3.如果无法处理，可重新panic

## 4. 小结

意料之中的：用error

意料之外的：用panic

组合使用：defer+panic+recover

